accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
app_name='account'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),

    path('', views.dashboard, name='dashboard'),
]

bookmarks/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('accounts.urls', namespace='account')),
    path('admin/', admin.site.urls),

]

accounts/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required


# dashboard view
@login_required
def dashboard(request):
    return render(request, 'accounts/dashboard.html',
                  {'section': 'dashboard'})

accounts/templates/accounts/dashboard.html
{% extends 'base.html' %}

{% block title %}Dashboard{% endblock %}

{% block content %}
    <h1>Dashboard</h1>
    <p>Welcome to the dashboard</p>
{% endblock %}

accounts/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link href="{% static 'css/base.css' %}" rel="stylesheet">

</head>

<body>
    <div id="header">
        <span class="logo">Bookmarks</span>
        {% if request.user.is_authenticated %}
            <ul class="menu">
            <li {% if section == "dashboard" %}class="selected"{% endif %}>
                <a href="{% url "account:dashboard" %}">My dashboard</a>
            </li>
            <li {% if section == "images" %}class="selected"{% endif %}>
                <a href="#">Images</a>
            </li>
            <li {% if section == "people" %}class="selected"{% endif %}>
                <a href="#">People</a>
            </li>
            </ul>
        {% endif %}

        <span class='user'>
        {% if request.user.is_authenticated %}
        Hello {{ request.user.first_name }},
        <a href="{% url "account:logout" %}">Logout</a>
        {% else %}
        <a href="{% url "account:login" %}">Log-in</a>
        {% endif %}
        </span>
    </div>


    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>